### ISSUE TITLE
Too tightly coupled with express 

### ISSUE THREAD

**Issue by faiq** [jaredhanson/passport#316]
Hey. I was trying to use this module along with routes-router module to do some simple routing for me, largely because I didn't need a giant framework like express to do things. Anyways when using the your module I ran into this error, and I think its because this module assumes that I'm using that middleware (maybe not). I'll post the error that I got below:

```
/Users/Faiq/Documents/googlesht/node_modules/passport/lib/middleware/authenticate.js:336
        next(err);
        ^
TypeError: object is not a function
    at Strategy.strategy.error (/Users/Faiq/Documents/googlesht/node_modules/passport/lib/middleware/authenticate.js:336:9)
    at Strategy.OAuthStrategy.authenticate (/Users/Faiq/Documents/googlesht/node_modules/passport-google-oauth/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:102:35)
    at attempt (/Users/Faiq/Documents/googlesht/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at Object.authenticate [as fn] (/Users/Faiq/Documents/googlesht/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Router.handleRequest (/Users/Faiq/Documents/googlesht/node_modules/routes-router/index.js:141:15)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2112:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1970:22)
    at TCP.onread (net.js:527:27)
```

Is it at all possible you'll want to support something that isn't middleware based?

**Comment by jaredhanson** [comment]
The only assumption Passport makes is that `req, res, next` is the function signature for processing requests.  That was popularized by Express, but isn't coupled to it.  If you want to use another calling convention, then you'll need to wrap Passport to adapt to it.

I personally don't find Express to be a "framework" (in the four-letter word sense that people like to throw around), and so I don't plan on spending time making Passport work with other calling conventions.

**Comment by faiq** [comment]
Thanks for the quick reply, and for clarifying some things up. I guess I could look into wrapping passport with my routes-router.
