### ISSUE TITLE
Passport and node --use_strict

### ISSUE THREAD

**Issue by danii1** [jaredhanson/passport#430]
I prefer to use strict mode everywhere, and quickly came across an issue with the passport when using `failureFlash: true` to display error message from strategy's verify callback.

Route
```javascript
router.post('/login', passport.authenticate('local-login', {
  successRedirect: 'profile',
  failureRedirect: 'login',
  failureFlash: true
}));
```

Verify Callback
```javascript
  ...
  if (!user) return done(null, false, { message: 'Invalid username.' }); 
```

In strict mode it throws error
```
TypeError: Cannot assign to read only property 'type' of true
    at allFailed (/home/daniil/Documents/Projects/test/express/node_modules/passport/lib/middleware/authenticate.js:106:20)
    at attempt (/home/daniil/Documents/Projects/test/express/node_modules/passport/lib/middleware/authenticate.js:160:28)
    at Strategy.strategy.fail (/home/daniil/Documents/Projects/test/express/node_modules/passport/lib/middleware/authenticate.js:277:9)
```

Problematic block in `passport/lib/middleware/authenticate.js`,  fails at `flash.type = flash.type || 'error';`, I think it's better to refactor this block to handle boolean values safely.
```javascript
if (options.failureFlash) {
  var flash = options.failureFlash;
  if (typeof flash == 'string') {
    flash = { type: 'error', message: flash };
  }
  flash.type = flash.type || 'error';

  var type = flash.type || challenge.type || 'error';
  msg = flash.message || challenge.message || challenge;
  if (typeof msg == 'string') {
    req.flash(type, msg);
  }
}
```

**Comment by ncurry01** [comment]
I am still seeing this error
TypeError: Cannot assign to read only property 'type' of true

using 
      if (options.failureFlash) {
        var flash = options.failureFlash;
        if (typeof flash == 'string') {
          flash = { type: 'error', message: flash };
        }
        flash.type = flash.type || 'error';
      
        var type = flash.type || challenge.type || 'error';
        msg = flash.message || challenge.message || challenge;
        if (typeof msg == 'string') {
          req.flash(type, msg);
        }
      }

**Comment by joevolcano** [comment]
I am still seeing this error
TypeError: Cannot assign to read only property 'type' of true

using
if (options.failureFlash) {
var flash = options.failureFlash;
if (typeof flash == 'string') {
flash = { type: 'error', message: flash };
}
flash.type = flash.type || 'error';

    var type = flash.type || challenge.type || 'error';
    msg = flash.message || challenge.message || challenge;
    if (typeof msg == 'string') {
      req.flash(type, msg);
    }
  }

**Comment by Hatko** [comment]
Is there any workaround for this problem?

**Comment by softmantk** [comment]
Any solution ????
