### ISSUE TITLE
Passport Works Intermittently

### ISSUE THREAD

**Issue by iammerrick** [jaredhanson/passport#440]
The same code will work sometimes, wait a few hours doesn't work, wait a few more hours it'll work great.  It happens with all the strategies (Facebook, Google, Twitter):

The error is: 

```
InternalOAuthError: Failed to obtain request token
   at Strategy.OAuthStrategy._createOAuthError (/code/node_modules/passport-oauth1/lib/strategy.js:352:17)
   at /code/node_modules/passport-oauth1/lib/strategy.js:218:41
   at /code/node_modules/oauth/lib/oauth.js:543:17
   at ClientRequest.<anonymous> (/code/node_modules/oauth/lib/oauth.js:421:9)
   at emitOne (events.js:77:13)
   at ClientRequest.emit (events.js:169:7)
   at TLSSocket.socketErrorListener (_http_client.js:265:9)
   at emitOne (events.js:77:13)
   at TLSSocket.emit (events.js:169:7)
   at connectErrorNT (net.js:996:8)
   at doNTCallback2 (node.js:450:9)
   at process._tickCallback (node.js:364:17)
```

**Comment by iammerrick** [comment]
Sorry this was an issue with docker resolving hosts...
