### ISSUE TITLE
failureFlash: true crashing

### ISSUE THREAD

**Issue by sgade** [jaredhanson/passport#464]
Using `passport.authenticate` with option `failureFlash: true` crashes. This method is explicitly documented in the [docs](http://passportjs.org/docs).

```javascript
node_modules/passport/lib/middleware/authenticate.js:113
        flash.type = flash.type || 'error';
                   ^

TypeError: Cannot assign to read only property 'type' of true
    at allFailed (/data/app/node_modules/passport/lib/middleware/authenticate.js:113:20)
    at attempt (/data/app/node_modules/passport/lib/middleware/authenticate.js:167:28)
    at Strategy.strategy.fail (/data/app/node_modules/passport/lib/middleware/authenticate.js:284:9)
    at verified (/data/app/node_modules/passport-local/lib/strategy.js:82:30)
    at Query.<anonymous> (/data/app/config/strategies/localStrategy.js:21:16)
    at /data/app/node_modules/kareem/index.js:177:19
    at /data/app/node_modules/kareem/index.js:109:16
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
```

Removing that specific line (`authenticate:133`) resolves the problem while not seeming to impact any functionality. Also, using an empty object for `failureFlash` works fine.
I am using Passport 0.3.2.

Is this a mistake in the documentation or a bug?

**Comment by BrendanFDMoore** [comment]
I've encountered this as well, still trying to work around it.
