### ISSUE TITLE
Configure multiple passports on two different apps (express 4.x)

### ISSUE THREAD

**Issue by pronebird** [jaredhanson/passport#465]
I am trying to configure two unrelated authorizations on my site. Essentially I have two apps and two passports. But currently I receive `Error: passport.initialize() middleware not in use`, which does not seem to be true.

```
Error: passport.initialize() middleware not in use
 at IncomingMessage.req.login.req.logIn (/Users/spaghetti-monster/node_modules/passport/lib/http/request.js:44:34)
 at Strategy.strategy.success (/Users/spaghetti-monster/node_modules/passport/lib/middleware/authenticate.js:228:13)
 at verified (/Users/spaghetti-monster/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:168:20)
 at Strategy._verify (/Users/spaghetti-monster/src/app.coffee:139:7)
 at /Users/spaghetti-monster/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:182:24
 at /Users/spaghetti-monster/node_modules/passport-twitter/lib/strategy.js:158:7
 at passBackControl (/Users/spaghetti-monster/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:390:11)
 at IncomingMessage.<anonymous> (/Users/spaghetti-monster/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:409:9)
 at emitNone (events.js:72:20)
 at IncomingMessage.emit (events.js:166:7)
 at endReadableNT (_stream_readable.js:903:12)
 at doNTCallback2 (node.js:439:9)
 at process._tickDomainCallback (node.js:394:17)
```

My source code:

```coffeescript
# Authentication
PassportClass        = require('passport').Passport
apiPassport            = new PassportClass()
adminPassport       = new PassportClass()

# Apps
app                      = express()
adminApp            = express()

# Routers
apiRouter              = express.Router()
adminRouter         = express.Router()

# authentication
apiPassport.use(
  new FacebookStrategy({
    clientID: process.env.FACEBOOK_APP_ID,
    clientSecret: process.env.FACEBOOK_APP_SECRET,
    callbackURL: urljoin(process.env.SITE_URL, '/api/v1/auth/facebook/callback'),
    profileFields: ['id', 'displayName', 'photos', 'email'],
    passReqToCallback: true
  },
  (req, accessToken, refreshToken, profile, done) ->
    saveUser req, profile, done
    return
  )
)

apiPassport.use(
  new SteamStrategy({
    returnURL: urljoin(process.env.SITE_URL, '/api/v1/auth/steam/callback'),
    realm: process.env.SITE_URL,
    apiKey: process.env.STEAM_API_KEY,
    passReqToCallback: true
  },
  (req, identifier, profile, done) ->
    saveUser req, profile, done
    return
  )
)

apiPassport.use new AnonymousStrategy()

apiPassport.use(
  new BearerStrategy({
      scope: 'all',
      passReqToCallback: true
    },
    (req, token, done) ->
      Token = mongoose.model 'Token'

      Token.findOne accessToken: token
        .populate 'holder'
        .exec (err, token) ->
          return done err  if err
          return done null, false  if not token

          req.token = token
          return done null, token.holder
  )
)

# admin authentication

adminPassport.use(
  new TwitterStrategy({
    consumerKey: process.env.TWITTER_CONSUMER_KEY,
    consumerSecret: process.env.TWITTER_CONSUMER_SECRET,
    callbackURL: urljoin(process.env.SITE_URL, '/admin/auth/callback')
  },
  (req, accessToken, refreshToken, profile, done) ->
    done null, id: profile.username
    return
  )
)

adminPassport.serializeUser (user, done) ->
  debug "serialize user.id: #{user.id}"
  done null, user.id
  return

adminPassport.deserializeUser (id, done) ->
  debug "deserialize user.id: #{id}"
  done null, id: id
  return

# setup session
# enable session only for /auth/ endpoint
app.use '/api/v1/auth*', session({
  name: 'sid',
  saveUninitialized: false,
  resave: false,
  secret: process.env.SESSION_SECRET || 'keyboard cat',
  store: new MongoStore(mongooseConnection: mongoose.connection)
})

adminApp.use session({
  name: 'admin.sid',
  saveUninitialized: false,
  resave: false,
  secret: process.env.SESSION_SECRET || 'keyboard cat',
  store: new MongoStore(mongooseConnection: mongoose.connection)
})

# setup passport
app.use '/api*', apiPassport.initialize()
app.use '/api*', apiPassport.session()

adminApp.use '/admin*', adminPassport.initialize()
adminApp.use '/admin*', adminPassport.session()

# configure admin app
adminApp.use adminRouter

# routing
app.use '/api/v1/', apiRouter
app.use '/admin/', adminApp # will mount adminApp -> app

# 404 handler
app.use (req, res, next) ->
  res.sendStatus 404
  return

```

**Comment by pronebird** [comment]
I had typo in my code I guess.
