### ISSUE TITLE
FaceBookTokenError

### ISSUE THREAD

**Issue by KarisNoder** [jaredhanson/passport#496]
FacebookTokenError: This authorization code has been used.
   at Strategy.parseErrorResponse (C:\Users\My pc\Music\BuddyApp\node_modules\passport-facebook\lib\strategy.js:196:12)
   at Strategy.OAuth2Strategy._createOAuthError (C:\Users\My pc\Music\BuddyApp\node_modules\passport-oauth2\lib\strategy.js:367:16)
   at C:\Users\My pc\Music\BuddyApp\node_modules\passport-oauth2\lib\strategy.js:166:45
   at C:\Users\My pc\Music\BuddyApp\node_modules\oauth\lib\oauth2.js:177:18
   at passBackControl (C:\Users\My pc\Music\BuddyApp\node_modules\oauth\lib\oauth2.js:123:9)
   at IncomingMessage.<anonymous> (C:\Users\My pc\Music\BuddyApp\node_modules\oauth\lib\oauth2.js:143:7)
   at emitNone (events.js:72:20)
   at IncomingMessage.emit (events.js:166:7)
   at endReadableNT (_stream_readable.js:913:12)
   at nextTickCallbackWith2Args (node.js:442:9)
   at process._tickCallback (node.js:356:17)

**Comment by farhankhwaja** [comment]
@jaredhanson can you help with this or provide a link which can help us solve this.
