### ISSUE TITLE
Error: passport.initialize() middleware not in use

### ISSUE THREAD

**Issue by scan** [jaredhanson/passport#51]
I get this error when I try to authenticate with the google OAuth2 strategy, the relevant code can be found [here](https://gist.github.com/dd5e39051f278b307cc0).

Now, when I navigate to `/auth/google`, I get properly redirected and my debug shows that I receive the profile. But then, node stops with the error:

```

DEBUG: /home/scan/JavaScript/ponyfolder/node_modules/mongoose/lib/utils.js:436

DEBUG:         throw err;

DEBUG:         
DEBUG:       ^

DEBUG: Error: passport.initialize() middleware not in use
    at IncomingMessage.req.login.req.logIn (/home/scan/JavaScript/ponyfolder/node_modules/passport/lib/passport/http/request.js:30:30)
    at Context.module.exports.delegate.success (/home/scan/JavaScript/ponyfolder/node_modules/passport/lib/passport/middleware/authenticate.js:174:13)
    at Context.actions.success (/home/scan/JavaScript/ponyfolder/node_modules/passport/lib/passport/context/http/actions.js:21:25)
    at verified (/home/scan/JavaScript/ponyfolder/node_modules/passport-google-oauth/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:133:18)
    at Promise.app.get.passport.authenticate.scope (/home/scan/JavaScript/ponyfolder/app/auth.coffee:34:16)
    at Promise.addBack (/home/scan/JavaScript/ponyfolder/node_modules/mongoose/lib/promise.js:128:8)
    at Promise.EventEmitter.emit (events.js:88:17)
    at Promise.emit (/home/scan/JavaScript/ponyfolder/node_modules/mongoose/lib/promise.js:66:38)
    at Promise.complete (/home/scan/JavaScript/ponyfolder/node_modules/mongoose/lib/promise.js:77:20)
    at cb (/home/scan/JavaScript/ponyfolder/node_modules/mongoose/lib/query.js:1392:32)
```

I have no idea where to go from there. First time using Mongoose, so perhaps I did something wrong there.

Using express 3 and mongoose 3.

**Comment by SampritiKakoty** [comment]
Yes passport initialization is mandatory.

I added 
router.use(passport.initialize());  

before actually using the code and it worked for me.

**Comment by J-Kazama** [comment]
What worked for me was putting:
```
app.use(passport.initialize());
app.use(passport.session());
```
before any other app.use.

**Comment by d-lokesh** [comment]
> What worked for me was putting:
> 
> ```
> app.use(passport.initialize());
> app.use(passport.session());
> ```
> 
> before any other app.use.

yes, it is wroking.

**Comment by mcali1** [comment]
yes this code works but you have but it before the router your using
 `app.use(passport.initialize());
app.use(passport.session());`
