### ISSUE TITLE
Python errors

### ISSUE THREAD

**Issue by AlexMunoz905** [jaredhanson/passport#523]
Hello, i have a error with passport. I even get the same error with passport-facebook. The error is asking for some python version. But i have python installed as i do python sometimes.

Here is the error:

```

> iconv@2.2.1 install /Users/alexmunoz/Documents/Code/Websites/express/node_modules/iconv
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Users/alexmunoz/miniconda3/bin/python" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:477:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/alexmunoz/Documents/Code/Websites/express/node_modules/iconv
gyp ERR! node -v v4.4.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
express@0.0.0 /Users/alexmunoz/Documents/Code/Websites/express
└── passport@0.3.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iconv@2.2.1 (node_modules/iconv):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iconv@2.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by AlexMunoz905** [comment]
Update: I just had to install python 2.
