### ISSUE TITLE
TypeError: Object #<IncomingMessage> has no method 'flash'

### ISSUE THREAD

**Issue by bitliner** [jaredhanson/passport#61]
Using Express 3, i get the following error:

```
TypeError: Object #<IncomingMessage> has no method 'flash'
    at allFailed (node_modules/passport/lib/passport/middleware/authenticate.js:110:15)
    at attempt (node_modules/passport/lib/passport/middleware/authenticate.js:211:28)
    at Context.module.exports.delegate.fail (node_modules/passport/lib/passport/middleware/authenticate.js:206:9)
    at Context.actions.fail (node_modules/passport/lib/passport/context/http/actions.js:35:22)
    at verified (node_modules/passport-local/lib/passport-local/strategy.js:82:30)
    at Promise.<anonymous> (routes/auth.js:10:12)
    at Promise.addBack (node_modules/mongoose/lib/promise.js:120:8)
    at Promise.EventEmitter.emit (events.js:88:17)
    at Promise.emit (node_modules/mongoose/lib/promise.js:59:38)
    at Promise.complete (node_modules/mongoose/lib/promise.js:70:20)

```

My code:
Login request handler

```
passport.authenticate('local', {
    successRedirect:'/dashboard',
    failureRedirect:'/login',
    failureFlash: true
})
```

Configuration

```
passport.authenticate('local', { failureFlash: 'Incorrect Username or Password!' });
```

I have tried to install connect-flash according to https://groups.google.com/forum/?fromgroups=#!topic/passportjs/9DWc4XJSEPk but nothig changes

**Comment by PrimeLens** [comment]
shouldn't connect-flash then be listed as a dependency for passport?
