### ISSUE TITLE
passport.authenticate('local', function (err, user, info) wrong values?

### ISSUE THREAD

**Issue by AncaElena10** [jaredhanson/passport#692]
> router.post('/login', function (req, res, next) {
>   passport.authenticate('local', function (err, user, info) {
>     console.log("1 err " + JSON.stringify(err))
>     console.log("2 user " + user)
>     console.log("3 info " + JSON.stringify(info))
>     if (err) { return res.status(501).json(err); }
>     if (!user) { return res.status(501).json(info); }
>     req.logIn(user, function (err) {
>       if (err) { return res.status(501).json(err); }
>       return res.status(200).json({ message: 'Login Success' });
>     });
>   })(req, res, next);
> });

I have this code but it's strange, because err, user and info are not the values are supposed to be.

err is `[{"id":1,"firstname":"a","lastname":"a","email":"a@gmail.com","password":"a"}]` (this info is from database)
user is `undefined`
info is `undefined`

I was expecting
err - `null`
user - `[{"id":1,"firstname":"a","lastname":"a","email":"a@gmail.com","password":"a"}]`
info `undefined`

I can provide more from my code, if you want. Thank you!

**Comment by joostdecock** [comment]
I have the same problem when using a JWT strategy. Express throws a 500 error, but even with all debug on doesn't complain about anything. So I setup a custom callback for the passport.authenticate() call, and the data received in the callback seems messed up.

As a reminder, [custom callbacks](http://www.passportjs.org/docs/authenticate/#custom-callback) have this signature:

```js
function(err, user, info)
``` 

My custom callback does this:

```js
console.log('In authenticate callback, arguments should be (err, user, info)', arguments);
```

Upon successful authentication I get:

```js
In authenticate callback, arguments should be (err, user, info) [Arguments] {
  '0':
   { _id: '5bd0376cdb30ea4002cf0f3c',
     handle: 'joost',
     aud: 'freesewing.org',
     iss: 'freesewing.org',
     iat: 1540485731 } }
```

As you can see, the callback gets only one argument which contains the decoded info in the token. However, as the first argument of the callback is supposed to hold the error, this is treated as an error.

For what it's worth, things seem better when I submit an invalid token:

```js
In authenticate callback, arguments should be (err, user, info) [Arguments] {
  '0': null,
  '1': false,
  '2':
   { JsonWebTokenError: invalid signature
       at /my/git/fon/backend/node_modules/jsonwebtoken/verify.js:122:19
       at getSecret (/my/git/fon/backend/node_modules/jsonwebtoken/verify.js:76:14)
       at Object.module.exports [as verify] (/my/git/fon/backend/node_modules/jsonwebtoken/verify.js:80:10)
       at Function.module.exports [as JwtVerifier] (/my/git/fon/backend/node_modules/passport-jwt/lib/verify_jwt.js:4:16)
       at /my/git/fon/backend/node_modules/passport-jwt/lib/strategy.js:104:25
       at JwtStrategy._secretOrKeyProvider (/my/git/fon/backend/node_modules/passport-jwt/lib/strategy.js:40:13)
       at JwtStrategy.authenticate (/my/git/fon/backend/node_modules/passport-jwt/lib/strategy.js:99:10)
       at attempt (/my/git/fon/backend/node_modules/passport/lib/middleware/authenticate.js:361:16)
       at authenticate (/my/git/fon/backend/node_modules/passport/lib/middleware/authenticate.js:362:7)
       at /my/git/fon/backend/build/webpack:/src/routes/user.js:63:7
       at Layer.handle [as handle_request] (/my/git/fon/backend/node_modules/express/lib/router/layer.js:95:5)
       at next (/my/git/fon/backend/node_modules/express/lib/router/route.js:137:13)
       at Route.dispatch (/my/git/fon/backend/node_modules/express/lib/router/route.js:112:3)
       at Layer.handle [as handle_request] (/my/git/fon/backend/node_modules/express/lib/router/layer.js:95:5)
       at /my/git/fon/backend/node_modules/express/lib/router/index.js:281:22
       at Function.process_params (/my/git/fon/backend/node_modules/express/lib/router/index.js:335:12) name: 'JsonWebTokenError', message: 'invalid signature' },
  '3': undefined }
```

Something is wrong here, but although I tried to figure it out, I can't wrap my head around it.
I came here to create an issue, only to see there's already one here. So what can we do to get to the bottom of this?

**Comment by joostdecock** [comment]
Ok, I figured this one out (in my case at least) and it's obviously my own fault.

When initializing my passport middleware (passport-jwt in my case), I had this:
```js
passport.use(new jwt.Strategy(options, (jwt_payload, done) => {
  return done(jwt_payload); 
}));
```

When it should have been:

```js
passport.use(new jwt.Strategy(options, (jwt_payload, done) => {
  return done(null, jwt_payload); 
}));
```

The first argument is the error. So even though everything was going fine, it was my own verify callback method that was not respecting the order of arguments. Because of course it was.

@AncaElena10 Perhaps this can help you.
As far as I'm concerned, this can be closed.
