### ISSUE TITLE
LinkedIn API V1 does not work anymore

### ISSUE THREAD

**Issue by grishick** [jaredhanson/passport#731]
LinkedIn has officially dropped support for V1 API (https://engineering.linkedin.com/blog/2018/12/developer-program-updates) and now passport-linkedin strategy stopped working. All callbacks get the following error message:

```
InternalOAuthError: failed to fetch user profile
       at /Users/gsolovyev/git/d4hv2/node_modules/passport-linkedin/lib/strategy.js:145:28
       at passBackControl (/Users/gsolovyev/git/d4hv2/node_modules/oauth/lib/oauth.js:397:13)
       at IncomingMessage.<anonymous> (/Users/gsolovyev/git/d4hv2/node_modules/oauth/lib/oauth.js:409:9)
       at IncomingMessage.emit (events.js:194:15)
       at IncomingMessage.EventEmitter.emit (domain.js:441:20)
       at endReadableNT (_stream_readable.js:1103:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
```
LinkedIn API returns HTTP 401 error code with message: 
`This resource is no longer available under v1 APIs`

**Comment by grishick** [comment]
BTW, this error is thrown with both _passport-linkedin_ and _passport-linkedin-oauth2_ strategies

**Comment by goatandsheep** [comment]
I think this needs to be posted in the [passport-linkedin repo](https://github.com/jaredhanson/passport-linkedin/issues)
