### ISSUE TITLE
VKontakte strategy: Invalid request: versions below 5.21 are deprecated.

### ISSUE THREAD

**Issue by alexey2baranov** [jaredhanson/passport#794]
### VKontakte strategy not works if you run example from doc

I ran example from http://www.passportjs.org/packages/passport-vk-strategy/
and got this error

```json
error: {
error_code: 8,
error_msg: "Invalid request: versions below 5.21 are deprecated. Version param should be passed as "v". "version" param is invalid and not supported. For more information go to https://vk.com/dev/constant_version_updates",
error_stack: "VkontakteAPIError: Invalid request: versions below 5.21 are deprecated. Version param should be passed as "v". "version" param is invalid and not supported. For more information go to https://vk.com/dev/constant_version_updates at /home/alexey/WebstormProjects/kopnik-node/node_modules/passport-vk-strategy/lib/strategy.js:166:29 at passBackControl (/home/alexey/WebstormProjects/kopnik-node/node_modules/oauth/lib/oauth2.js:134:9) at IncomingMessage.<anonymous> (/home/alexey/WebstormProjects/kopnik-node/node_modules/oauth/lib/oauth2.js:157:7) at IncomingMessage.emit (node:events:388:22) at endReadableNT (node:internal/streams/readable:1305:12) at processTicksAndRejections (node:internal/process/task_queues:80:21)"
}
``` 

### Expected behavior
should redirect to vk.com and ask creds

### Actual behavior
throws error as under

### Steps to reproduce
just run example from documentation http://www.passportjs.org/packages/passport-vk-strategy/

### Environment

* Operating System: Linux
* Node version:15.1.0
* passport version: 0.4.1

**Comment by jaredhanson** [comment]
This issue should be reported to the maintainer of [passport-vk-strategy](https://github.com/dvpnt/passport-vk-strategy).
