### ISSUE TITLE
v0.5.0 Breaking changes in tests

### ISSUE THREAD

**Issue by MrSwitch** [jaredhanson/passport#858]
Tests are failing on the line...

https://github.com/jaredhanson/passport/blob/ff4450692b4fbc62b8f425a70299571158281a16/lib/strategies/session.js#L51

I presume `req.session` is not defined and `this._key` = 'passport'. I'm not sure how to get req.session populated. The tests are setup so that `app.req(passport.initialize());` and `app.req(passport.session());` are defined - which i've read about in other breaking change issues.

> Change Password
  TypeError: Cannot read property 'passport' of undefined
    at SessionStrategy.authenticate (/Users/andrew.dodson/workspace/hub/auth/node_modules/passport/lib/strategies/session.js:51:18)
    at attempt (/Users/andrew.dodson/workspace/hub/auth/node_modules/passport/lib/middleware/authenticate.js:360:16)
    at authenticate (/Users/andrew.dodson/workspace/hub/auth/node_modules/passport/lib/middleware/authenticate.js:361:7)
    at newFn (/Users/andrew.dodson/workspace/hub/auth/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:317:13)
    at /Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:275:10)
    at initialize (/Users/andrew.dodson/workspace/hub/auth/node_modules/passport/lib/middleware/initialize.js:66:5)
    at newFn (/Users/andrew.dodson/workspace/hub/auth/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:317:13)
    at /Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:275:10)
    at file:///Users/andrew.dodson/workspace/hub/auth/test/specs/auth/change-password.js:22:2
    at newFn (/Users/andrew.dodson/workspace/hub/auth/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:317:13)
    at /Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/Users/andrew.dodson/workspace/hub/auth/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at newFn (/Users/andrew.dodson/workspace/hub/auth/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:317:13)
    at /Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/andrew.dodson/workspace/hub/auth/node_modules/express/lib/router/index.js:275:10)
    at /Users/andrew.dodson/workspace/hub/auth/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/Users/andrew.dodson/workspace/hub/auth/node_modules/raw-body/index.js:224:16)
    at done (/Users/andrew.dodson/workspace/hub/auth/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/andrew.dodson/workspace/hub/auth/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:388:22)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    1) should process a POST request to the auth/change-password endpoint

**Comment by jaredhanson** [comment]
Are you referring to your application's test suite, or Passport's own test suite?

**Comment by MrSwitch** [comment]
This is the result of my own application test suite.
