### ISSUE TITLE
Failed to obtain access token

### ISSUE THREAD

**Issue by ARR4NN** [jaredhanson/passport#932]
```
Error: Failed to obtain access token
    at C:\Users\User\Documents\Websites\MemberManager\API\node_modules\passport-oauth2\lib\strategy.js:178:49
    at C:\Users\User\Documents\Websites\MemberManager\API\node_modules\oauth\lib\oauth2.js:209:7
    at passBackControl (C:\Users\User\Documents\Websites\MemberManager\API\node_modules\oauth\lib\oauth2.js:134:9)
    at IncomingMessage.<anonymous> (C:\Users\User\Documents\Websites\MemberManager\API\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
This happens after the code in the URL bar is invalid. I find it happening after redirecting and the token being invalid

**Comment by jaredhanson** [comment]
If the code in the URL bar is invalid, it would be expected that an access token cannot be obtained.

**Comment by ARR4NN** [comment]
Yeah but i want to be able to control that error like replacing it with my own error. Is that possible

**Comment by jaredhanson** [comment]
You can add error handling middleware like so:

```
app.get('/oauth2/callback', passport.authenticate(...),
  function(err, req, res, next) {
    // Check for errors you want to replace and handle it appropriately
    // else
    // next(err);
  }
```

**Comment by ARR4NN** [comment]
That doesn't appear to be working for me

**Comment by ARR4NN** [comment]
```
router.get('/',
    passport.authenticate('github', { scope: ['user:email', 'read:user'] }),
    function (err, req, res, next) {
        // Check `err` for errors you want to replace and handle it appropriately
        console.log("hell yeah")
        // else
        next(err);
    }
)
```

**Comment by jaredhanson** [comment]
You need to put the error handling on the callback route, not the route that redirects to GitHub.

**Comment by ARR4NN** [comment]
i did try that too

**Comment by ARR4NN** [comment]
```router.get('/callback', passport.authenticate('github'),
    function (err, req, res, next) {
        // Check `err` for errors you want to replace and handle it appropriately
        console.log("hell yeah")
        // else
        next(err);
    }
)```

**Comment by ARR4NN** [comment]
my strat is 
```
const strategy = new GitHubStrategy({
    clientID: GITHUB_CLIENT_ID,
    clientSecret: GITHUB_CLIENT_SECRET,
    callbackURL: "http://localhost:3001/api/auth/github/callback",
    passReqToCallback: true,
}, async function (req, accessToken, refreshToken, profile, done) {
    ......
});

passport.use(strategy)
```
